In [1]:
import pandas as pd

In [70]:
# Path to the parquet file
parquet_file_path = '/fast/pmayilvahanan/datasets/gsm8k/train.parquet'

# Load the parquet file into a pandas DataFrame
df_gsm8k = pd.read_parquet(parquet_file_path)

df_math = pd.read_parquet('/fast/pmayilvahanan/datasets/math/train.parquet')


df_curated = pd.read_parquet('/fast/pmayilvahanan/datasets/curated_thoughts_0_3/train-00000-of-00010.parquet')

df_curated_final = pd.read_parquet('/fast/pmayilvahanan/datasets/curated_thoughts/train.parquet')





In [111]:
df_deepscaler = pd.read_parquet('/fast/pmayilvahanan/datasets/deepscaler/train.parquet')

In [116]:
df_deepscaler

data_source  \
0      agentica-org/DeepScaleR-Preview-Dataset   
1      agentica-org/DeepScaleR-Preview-Dataset   
2      agentica-org/DeepScaleR-Preview-Dataset   
3      agentica-org/DeepScaleR-Preview-Dataset   
4      agentica-org/DeepScaleR-Preview-Dataset   
...                                        ...   
36279  agentica-org/DeepScaleR-Preview-Dataset   
36280  agentica-org/DeepScaleR-Preview-Dataset   
36281  agentica-org/DeepScaleR-Preview-Dataset   
36282  agentica-org/DeepScaleR-Preview-Dataset   
36283  agentica-org/DeepScaleR-Preview-Dataset   

                                                  prompt ability  \
0      [{'content': 'Given that 800 students were sur...    math   
1      [{'content': 'Two circles with centers $A$ and...    math   
2      [{'content': 'In our province, the new college...    math   
3      [{'content': 'The number \( N \) has the small...    math   
4      [{'content': 'A certain agency has 18 elderly,...    math   
...                                                  ...     ...   
36279  [{'content': 'On the refrigerator, MATHEMATICS...    math   
36280  [{'content': 'Suppose that $m$ and $n$ are int...    math   
36281  [{'content': 'Cube $A B C D E F G H$ has edge ...    math   
36282  [{'content': 'Given the function $f(x)=kx+b$, ...    math   
36283  [{'content': 'The hares are cutting the log ag...    math   

                                            reward_model  \
0       {'ground_truth': '\frac{4}{3}', 'style': 'rule'}   
1      {'ground_truth': '\frac{15 \sqrt{2}}{8}', 'sty...   
2                {'ground_truth': '92', 'style': 'rule'}   
3               {'ground_truth': '260', 'style': 'rule'}   
4             {'ground_truth': 'X = 6', 'style': 'rule'}   
...                                                  ...   
36279            {'ground_truth': '72', 'style': 'rule'}   
36280            {'ground_truth': '29', 'style': 'rule'}   
36281            {'ground_truth': '28', 'style': 'rule'}   
36282            {'ground_truth': '-3', 'style': 'rule'}   
36283            {'ground_truth': '11', 'style': 'rule'}   

                                              extra_info  
0      {'full_solution': '', 'index': 0, 'split': 'tr...  
1      {'full_solution': '', 'index': 1, 'split': 'tr...  
2      {'full_solution': '', 'index': 2, 'split': 'tr...  
3      {'full_solution': '', 'index': 3, 'split': 'tr...  
4      {'full_solution': '', 'index': 4, 'split': 'tr...  
...                                                  ...  
36279  {'full_solution': '', 'index': 36279, 'split':...  
36280  {'full_solution': 'If $n$ is even, $n+1 \mid n...  
36281  {'full_solution': 'Triangular-based pyramid $A...  
36282  {'full_solution': '', 'index': 36282, 'split':...  
36283  {'full_solution': '', 'index': 36283, 'split':...  

[36284 rows x 5 columns]

In [97]:
df_curated_final

solution  \
0      ## Solution.\n\nLet $t$ be the time required f...   
1      3. (6 points) A construction company builds a ...   
2                                                    $D$   
3      1. $\frac{8 x+13}{3}=\frac{19-12 x}{2}-\left(1...   
4      Let the lengths of the legs be $a$ and $b$, an...   
...                                                  ...   
88657  6) The answer is $(\mathbf{D})$.\n\nIndeed, $\...   
88658  Solution. We will use the formulas for the squ...   
88659  Calculate the number of pairs of connected sub...   
88660  1. We need to determine the number of integers...   
88661  10. Answer. 8\nSolution. We consider the polyn...   

      is_reasoning_complete  \
0              [True, True]   
1              [True, True]   
2              [True, True]   
3              [True, True]   
4              [True, True]   
...                     ...   
88657          [True, True]   
88658          [True, True]   
88659                [True]   
88660          [True, True]   
88661          [True, True]   

                                             generations  \
0      [<think>\nOkay, so I need to find the speed of...   
1      [<think>\nOkay, let me try to figure out this ...   
2      [<think>\nOkay, so I have this problem here wh...   
3      [<think>\nOkay, so I need to solve this equati...   
4      [<think>\nOkay, so I need to figure out the po...   
...                                                  ...   
88657  [<think>\nOkay, let's see. The problem is aski...   
88658  [<think>\nOkay, so I have this expression to s...   
88659  [<think>\nOkay, let's see. The problem is abou...   
88660  [<think>\nOkay, so I need to find the differen...   
88661  [<think>\nOkay, so I need to find the maximum ...   

      correctness_math_verify correctness_llama finish_reasons  \
0               [True, False]              None           None   
1                [True, True]              None           None   
2                [True, True]              None           None   
3                [True, True]              None           None   
4                [True, True]              None           None   
...                       ...               ...            ...   
88657          [False, False]      [True, True]           None   
88658            [True, True]              None   [stop, stop]   
88659                 [False]            [True]           None   
88660            [True, True]              None           None   
88661            [True, True]              None           None   

       correctness_count                                           messages  \
0                      1  [{'from': 'user', 'value': '## Task B-1.3.

A ...   
1                      2  [{'from': 'user', 'value': '3. (6 points) A co...   
2                      2  [{'from': 'user', 'value': '4. Given the three...   
3                      2  [{'from': 'user', 'value': '1. Solve the equat...   
4                      2  [{'from': 'user', 'value': 'A right-angled tri...   
...                  ...                                                ...   
88657                  2  [{'from': 'user', 'value': '6) What is the val...   
88658                  2  [{'from': 'user', 'value': '385. $(\tan \alpha...   
88659                  1  [{'from': 'user', 'value': 'In a communication...   
88660                  2  [{'from': 'user', 'value': 'Let $n$ be a posit...   
88661                  2  [{'from': 'user', 'value': '10. Given that
$$
...   

                type                data_source  \
0            Algebra  bethgelab/CuratedThoughts   
1            Algebra  bethgelab/CuratedThoughts   
2           Geometry  bethgelab/CuratedThoughts   
3            Algebra  bethgelab/CuratedThoughts   
4           Geometry  bethgelab/CuratedThoughts   
...              ...                        ...   
88657        Algebra  bethgelab/CuratedThoughts   
88658        Algebra  bethgelab/CuratedThoughts   
88659  Combinatorics  bethgelab/

In [88]:
df_aime = pd.read_parquet('/fast/pmayilvahanan/datasets/aime_2024/test.parquet')
df_gpqa = pd.read_parquet('/fast/pmayilvahanan/datasets/gpqa_diamond/test.parquet')

In [96]:
df_aime.iloc[0]['prompt']

array([{'content': "Every morning Aya goes for a $9$-kilometer-long walk and stops at a coffee shop afterwards. When she walks at a constant speed of $s$ kilometers per hour, the walk takes her 4 hours, including $t$ minutes spent in the coffee shop. When she walks $s+2$ kilometers per hour, the walk takes her 2 hours and 24 minutes, including $t$ minutes spent in the coffee shop. Suppose Aya walks at $s+\\frac{1}{2}$ kilometers per hour. Find the number of minutes the walk takes her, including the $t$ minutes spent in the coffee shop. Let's think step by step and output the final answer within \\boxed{}.", 'role': 'user'}],
      dtype=object)

In [92]:
df_aime.iloc[0]['reward_model']

{'ground_truth': '204', 'style': 'rule'}

In [83]:
for i in range(100):
    print(len(df_curated_final.iloc[i]['solution']))

1673
826
3
495
2545
1831
1116
772
58
404
1388
554
406
374
544
1914
1229
186
19
455
690
20
12
1981
223
807
825
872
556
571
127
636
287
1499
652
4679
19
285
179
299
611
542
315
848
591
1914
371
1000
621
516
2344
899
869
176
596
320
708
219
632
217
1756
1231
392
195
842
1900
1776
474
1035
944
2613
697
1148
841
2403
355
841
778
188
219
624
1232
527
732
2945
1481
1749
452
491
946
146
6
1126
727
361
907
683
693
1017
464


In [77]:
df_curated_final.iloc[100]['reward_model']

{'ground_truth': '80', 'style': 'rule'}

In [67]:
df_gsm8k.iloc[0]['extra_info']

{'answer': 'Natalia sold 48/2 = <<48/2=24>>24 clips in May.\nNatalia sold 48+24 = <<48+24=72>>72 clips altogether in April and May.\n#### 72',
 'index': 0,
 'question': 'Natalia sold clips to 48 of her friends in April, and then she sold half as many clips in May. How many clips did Natalia sell altogether in April and May?',
 'split': 'train'}

In [17]:
df_math

level         type                         data_source  \
0     Level 5      Algebra  DigitalLearningGmbH/MATH-lighteval   
1     Level 5      Algebra  DigitalLearningGmbH/MATH-lighteval   
2     Level 3      Algebra  DigitalLearningGmbH/MATH-lighteval   
3     Level 3      Algebra  DigitalLearningGmbH/MATH-lighteval   
4     Level 3      Algebra  DigitalLearningGmbH/MATH-lighteval   
...       ...          ...                                 ...   
7495  Level 3  Precalculus  DigitalLearningGmbH/MATH-lighteval   
7496  Level 2  Precalculus  DigitalLearningGmbH/MATH-lighteval   
7497  Level 2  Precalculus  DigitalLearningGmbH/MATH-lighteval   
7498  Level 2  Precalculus  DigitalLearningGmbH/MATH-lighteval   
7499  Level 2  Precalculus  DigitalLearningGmbH/MATH-lighteval   

                                                 prompt ability  \
0     [{'content': 'Let \[f(x) = \left\{
\begin{arra...    math   
1     [{'content': 'A rectangular band formation is ...    math   
2     [{'content': 'What is the degree of the polyno...    math   
3     [{'content': 'Evaluate $\left\lceil3\left(6-\f...    math   
4     [{'content': 'Sam is hired for a 20-day period...    math   
...                                                 ...     ...   
7495  [{'content': 'Find the number of real solution...    math   
7496  [{'content': 'Let $A,$ $B,$ $C$ be the angles ...    math   
7497  [{'content': 'Let $G$ be the centroid of trian...    math   
7498  [{'content': 'If angle $A$ lies in the second ...    math   
7499  [{'content': 'The real numbers $a$ and $b$ sat...    math   

                                           reward_model  \
0                {'ground_truth': '0', 'style': 'rule'}   
1               {'ground_truth': '98', 'style': 'rule'}   
2                {'ground_truth': '4', 'style': 'rule'}   
3               {'ground_truth': '17', 'style': 'rule'}   
4                {'ground_truth': '6', 'style': 'rule'}   
...                                                 ...   
7495            {'ground_truth': '63', 'style': 'rule'}   
7496             {'ground_truth': '0', 'style': 'rule'}   
7497             {'ground_truth': '3', 'style': 'rule'}   
7498  {'ground_truth': '-\frac{\sqrt{7}}{4}', 'style...   
7499  {'ground_truth': '\left( \frac{8}{5}, -\frac{3...   

                             extra_info  
0        {'index': 0, 'split': 'train'}  
1        {'index': 1, 'split': 'train'}  
2        {'index': 2, 'split': 'train'}  
3        {'index': 3, 'split': 'train'}  
4        {'index': 4, 'split': 'train'}  
...                                 ...  
7495  {'index': 7495, 'split': 'train'}  
7496  {'index': 7496, 'split': 'train'}  
7497  {'index': 7497, 'split': 'train'}  
7498  {'index': 7498, 'split': 'train'}  
7499  {'index': 7499, 'split': 'train'}  

[7500 rows x 7 columns]

In [45]:
from datasets import load_dataset

# Login using e.g. `huggingface-cli login` to access this dataset
ds = load_dataset("bethgelab/CuratedThoughts", "OpenR1-Math-220k-default")

README.md:   0%|          | 0.00/8.67k [00:00<?, ?B/s]

train-00000-of-00010.parquet:   0%|          | 0.00/199M [00:00<?, ?B/s]

train-00001-of-00010.parquet:   0%|          | 0.00/199M [00:00<?, ?B/s]

train-00002-of-00010.parquet:   0%|          | 0.00/199M [00:00<?, ?B/s]

train-00003-of-00010.parquet:   0%|          | 0.00/202M [00:00<?, ?B/s]

train-00004-of-00010.parquet:   0%|          | 0.00/199M [00:00<?, ?B/s]

train-00005-of-00010.parquet:   0%|          | 0.00/199M [00:00<?, ?B/s]

train-00006-of-00010.parquet:   0%|          | 0.00/201M [00:00<?, ?B/s]

train-00007-of-00010.parquet:   0%|          | 0.00/201M [00:00<?, ?B/s]

train-00008-of-00010.parquet:   0%|          | 0.00/198M [00:00<?, ?B/s]

train-00009-of-00010.parquet:   0%|          | 0.00/200M [00:00<?, ?B/s]

Generating train split:   0%|          | 0/88662 [00:00<?, ? examples/s]

In [62]:
for i in range(1000):
    if len(ds['train'][i]['solution']) < 100:
        print(i)

2
8
18
21
22
36
91
113
125
157
225
292
295
345
354
367
370
379
386
391
440
487
513
553
605
620
628
632
653
679
690
698
704
724
730
759
791
793
825
836
841
856
901
920
946
950
965
971
972
974
989
996


In [69]:
ds['train'][0]

{'problem': '## Task B-1.3.\n\nA ship traveling along a river has covered $24 \\mathrm{~km}$ upstream and $28 \\mathrm{~km}$ downstream. For this journey, it took half an hour less than for traveling $30 \\mathrm{~km}$ upstream and $21 \\mathrm{~km}$ downstream, or half an hour more than for traveling $15 \\mathrm{~km}$ upstream and $42 \\mathrm{~km}$ downstream, assuming that both the ship and the river move uniformly.\n\nDetermine the speed of the ship in still water and the speed of the river.',
 'solution': '## Solution.\n\nLet $t$ be the time required for the boat to travel $24 \\mathrm{~km}$ upstream and $28 \\mathrm{~km}$ downstream, $v_{R}$ the speed of the river, and $v_{B}$ the speed of the boat. When the boat is traveling upstream, its speed is $v_{B}-v_{R}$, and when it is traveling downstream, its speed is $v_{B}+v_{R}$.\n\nSince $t=\\frac{s}{v}$, from the given data, we obtain the following system of equations:\n\n$\\left\\{\\begin{array}{l}t=\\frac{24}{v_{B}-v_{R}}+\\fra

In [60]:
df_math.iloc[0].to_dict()

{'level': 'Level 5',
 'type': 'Algebra',
 'data_source': 'DigitalLearningGmbH/MATH-lighteval',
 'prompt': array([{'content': "Let \\[f(x) = \\left\\{\n\\begin{array}{cl} ax+3, &\\text{ if }x>2, \\\\\nx-5 &\\text{ if } -2 \\le x \\le 2, \\\\\n2x-b &\\text{ if } x <-2.\n\\end{array}\n\\right.\\]Find $a+b$ if the piecewise function is continuous (which means that its graph can be drawn without lifting your pencil from the paper). Let's think step by step and output the final answer within \\boxed{}.", 'role': 'user'}],
       dtype=object),
 'ability': 'math',
 'reward_model': {'ground_truth': '0', 'style': 'rule'},
 'extra_info': {'index': 0, 'split': 'train'}}

In [68]:
df_gsm8k.iloc[0].to_dict()

{'data_source': 'openai/gsm8k',
 'prompt': array([{'content': 'Natalia sold clips to 48 of her friends in April, and then she sold half as many clips in May. How many clips did Natalia sell altogether in April and May? Let\'s think step by step and output the final answer after "####".', 'role': 'user'}],
       dtype=object),
 'ability': 'math',
 'reward_model': {'ground_truth': '72', 'style': 'rule'},
 'extra_info': {'answer': 'Natalia sold 48/2 = <<48/2=24>>24 clips in May.\nNatalia sold 48+24 = <<48+24=72>>72 clips altogether in April and May.\n#### 72',
  'index': 0,
  'question': 'Natalia sold clips to 48 of her friends in April, and then she sold half as many clips in May. How many clips did Natalia sell altogether in April and May?',
  'split': 'train'}}

In [84]:
from datasets import load_dataset

ds = load_dataset("HuggingFaceH4/aime_2024")

README.md:   0%|          | 0.00/932 [00:00<?, ?B/s]

train-00000-of-00001.parquet:   0%|          | 0.00/81.7k [00:00<?, ?B/s]

Generating train split:   0%|          | 0/30 [00:00<?, ? examples/s]

In [85]:
ds

DatasetDict({
    train: Dataset({
        features: ['id', 'problem', 'solution', 'answer', 'url', 'year'],
        num_rows: 30
    })
})

In [86]:
from datasets import load_dataset

ds = load_dataset("hendrydong/gpqa_diamond")

README.md:   0%|          | 0.00/339 [00:00<?, ?B/s]

test-00000-of-00001.parquet:   0%|          | 0.00/61.6k [00:00<?, ?B/s]

Generating test split:   0%|          | 0/198 [00:00<?, ? examples/s]

In [87]:
ds

DatasetDict({
    test: Dataset({
        features: ['solution', 'problem', 'domain'],
        num_rows: 198
    })
})

In [103]:
import numpy as np
temp = np.array([1, 1, 1, 1, 0])+0.0
mean_temp = np.mean(temp)
std_temp = np.std(temp)
temp-=mean_temp
temp/=std_temp
temp

array([ 0.5,  0.5,  0.5,  0.5, -2. ])

In [104]:
import numpy as np
temp = np.array([1, 0, 0, 0, 0])+0.0
mean_temp = np.mean(temp)
std_temp = np.std(temp)
temp-=mean_temp
temp/=std_temp
temp

array([ 2. , -0.5, -0.5, -0.5, -0.5])

In [105]:
import numpy as np
temp = np.array([1, 1, 1, 0, 0])+0.0
mean_temp = np.mean(temp)
std_temp = np.std(temp)
temp-=mean_temp
temp/=std_temp
temp

array([ 0.81649658,  0.81649658,  0.81649658, -1.22474487, -1.22474487])

In [106]:
import numpy as np
temp = np.array([1, 1, 0, 0, 0])+0.0
mean_temp = np.mean(temp)
std_temp = np.std(temp)
temp-=mean_temp
temp/=std_temp
temp

array([ 1.22474487,  1.22474487, -0.81649658, -0.81649658, -0.81649658])

In [107]:
from datasets import load_dataset

# Login using e.g. `huggingface-cli login` to access this dataset
ds = load_dataset("agentica-org/DeepScaleR-Preview-Dataset")

README.md:   0%|          | 0.00/1.78k [00:00<?, ?B/s]

deepscaler.json:   0%|          | 0.00/21.5M [00:00<?, ?B/s]

Generating train split:   0%|          | 0/40315 [00:00<?, ? examples/s]

In [108]:
ds

DatasetDict({
    train: Dataset({
        features: ['problem', 'answer', 'solution'],
        num_rows: 40315
    })
})